version: "3"

services:
  neo4j:
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: "neo4j/j4oen"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - "neo4j-data:/data"
    restart: unless-stopped

volumes:
  neo4j-data: {}
